apiVersion: 1.0
image:
    imageType: raw
    arch: aarch64 
    baseImage: SL-Micro.aarch64-6.0-Default-GM.raw
    outputImageName: elemental-6.0.raw
operatingSystem:
  users:
    - username: root
      encryptedPassword: $6$jHugJNNd3HElGsUZ$eodjVe4te5ps44SVcWshdfWizrP.xAyd71CVEXazBJ/.v799/WRCBXxfYmunlBO2yp1hm/zb4r8EmnrrNCF.P/
